### ISSUE TITLE
Remove lookups to inactive records so they aren't exported by the PAC

### ISSUE THREAD

**Issue by z424brave** [Cloud-Awesome/power-portal-gds-accelerator#7]
Hi
I am working in Defra and was trying to use this repo to learn about the potential for using power portals on a Defra project.
I am getting the following errors when trying to upload the site configuration

```
Updating table adx_webpage with record id:3b8cafb5-3ebd-ea11-a812-000d3a7fedbe FAILED due to Adx_weblinkset With Id = 0866571f-a3da-e711-a94d-000d3a2bb81e Does Not Exist
Updating table adx_webpage with record id:3b8cafb5-3ebd-ea11-a812-000d3a7fedbe FAILED due to Adx_weblinkset With Id = 0866571f-a3da-e711-a94d-000d3a2bb81e Does Not Exist
```

I don't believe this is a bug so I have raised it as a question to see if you could shed any light on why this might be occurring.

**Comment by Cloud-Awesome** [comment]
Hi there, thanks for raising this!

This is issue is being caused due to a little quirk in the PAC CLI, which has exported a lookup to a deactivated record, but hasn't actually exported the deactivated record itself (a weblink set called Task List Links)

I'll make a new export and test successful upload on a clean portal instance during the week then will publish a new version.

In the meantime, you can manually work around this by simply deleting any missing references in the offending yaml file(s), e.g. in the case mentioned above, this is the offending line:

https://github.com/Cloud-Awesome/power-portal-gds-accelerator/blob/b2690b39e018be2f3a2d7827ff9802dcdb83c5f9/src/gds-portal-accelerator/web-pages/build/content-pages/Build.en-US.webpage.yml#L10

Deleting the line entirely before uploading to your environment shouldn't have any adverse effects as it's only an example implementation of a web page.

Hope this helps and I'll close this issue off in a few days when I publish a fixed version
