### ISSUE TITLE
Question: How should security be set up to use out of the box

### ISSUE THREAD

**Issue by z424brave** [Cloud-Awesome/power-portal-gds-accelerator#8]
Hi
After the bug fix the config now loads without error but I have a question on how the resulting portal app should be configured for security. It appears that when clicking "Start Now" from the home page I get taken to a "sign-in" page which is enabled for "local login". There are no options to register a new login  - does this mean I need to create a user in `Portal Management` and then use the credentials of that user.

**Comment by apng1982** [comment]
Hi there,

The easiest/quickest way to get through is to create a new contact login in the Portal Management app in Dynamics (using the 'Portal Contact' form) as you suggest.

![image](https://user-images.githubusercontent.com/42772282/156028006-3acbaa51-8829-44ad-bbdc-ac7d3930559f.png)

That said, the accelerator is only meant to get GDS styling and patterns from the design system up and running in PA Portals for further customisation to specific needs for your service. **Best practice is to integrate with Azure AD B2C, not to use local authentication** which is why I didn't put much work into a local registration process 

There is a [sample Web Template for B2C](https://github.com/Cloud-Awesome/power-portal-gds-accelerator/tree/master/src/gds-portal-accelerator/web-templates/b2c-login-page-template) but [some set up required for it to work for your tenant](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/configure-azure-ad-b2c-provider-manual). If you're just using this as a proof of concept sandbox for PA Portals in general, then local auth is fine.

For info, you're being asked to log in because there is a Web Page Access Control rule on the 2nd page, which requires the user to authenticated.

![image](https://user-images.githubusercontent.com/42772282/156028346-29995b20-7f89-4f5f-b5d0-243e29926df8.png)

Technically you could disable this, but further pages are based on the logged in contact so wouldn't work.

Hope that helps! :)
